#!/usr/bin/env bash
docker-compose exec app rm .env.local
docker-compose exec app cp .env.docker .env.local

docker-compose exec app composer install

# start fresh
docker-compose exec app bin/console doctrine:database:drop --force
docker-compose exec app bin/console doctrine:database:create
docker-compose exec app bin/console doctrine:schema:create
docker-compose exec app bin/console doctrine:fixtures:load -n

docker-compose exec app yarn install
docker-compose exec app yarn dev
